import React from 'react';

import styles from './styles.css';

export default class TermsPage extends React.Component { // eslint-disable-line react/prefer-stateless-function
  render() {
    return (<div className={styles.terms}>
      <h1>Terms of use</h1>
      <section>
        <h2>Terms for use of this site</h2>
        <p>This site has been built by IMIN LTD in association with London Sport Trading Ltd. You agree that you will not copy, store in any medium, distribute, transmit, modify or show in public any part of the website without the prior written permission of London Sport Trading Ltd or in accordance with the copyright, Design and Patents Act 1988.</p>
        <h2>Accuracy</h2>
        <p>Every effort has been made to ensure that the information contained in this website is accurate and up to date. IMIN LTD or London Sport Trading Ltd does not accept legal liability for errors or omissions and reserves the right to make changes to some or all the information contained in this site without notice. Where there are links to external websites, we do not accept responsibility for the content on those sites.</p>
        <p>The contents of this website do not necessarily represent the opinions, views, policy or procedures of IMIN LTD or London Sport Trading Ltd. Please note that IMIN LTD or London Sport Trading Ltd does not warrant that the website or any attachments are free from viruses or other defects and accepts no liability for any losses resulting from infected interactions with the website.</p>
        <p>The information contained on this website has been provided by third parties (activity providers) independent of IMIN LTD or London Sport Trading Ltd. IMIN LTD and London Sport Trading Ltd accept no liability for any illegality arising from error or omissions or inaccuracy in such material and take no responsibility for such material. IMIN LTD and London Sport Trading Ltd will seek to remove any such erroneous or inaccurate material, and any material that is obscene, offensive, defamatory or discriminatory. Before providing information about activities, it is strongly recommended that you make <a href="http://www.getactivelondon.com/page.asp?section=226&amp;sectionTitle=Play+Safe">appropriate checks</a> to ensure high quality provision and a safe environment is provided. IMIN LTD and London Sport Trading Ltd accept no liability (to the full extent permitted by law) for the quality of the activities provided.</p>
        <p>You acknowledge and agree that you alone are responsible for any and all content and images you upload on this website, and that activities must not be inaccurate, false, misleading, or obscene. You understand that images are intended only to indicate a photographic representation of the activity and IMIN LTD or London Sport Trading Ltd reserve the right to remove from this website images that breach copyright, are obscene, offensive, defamatory or discriminatory.</p>
        <h2>Your Privacy</h2>
        <p>It is important that your privacy is protected whenever you provide any information during your use of this website. Should we ask you to provide certain information by which you can be identified when using our website, then you can be assured that it will only be used in accordance with this Privacy Policy!</p>
        <h2>What information do we collect?</h2>
        <p>We may collect the following information: name; email address; demographic information, for example postcode, preferences and interests; and any other information relevant to the provision of our service to you.</p>
        <h2>What do we do with the information we gather?</h2>
        <p>We require this information to provide you with a more comprehensive service. In order to do this, we might periodically send emails to the email address provided about our products and services that we think you will find interesting, based on the information you have provided to us, in order to help us to customise the website according to your interests.</p>
        <h2>Can you control your personal information?</h2>
        <p>Because of the nature of the service we provide, we may use your personal information to send you promotional information about third parties which we think you may find interesting if you tell us that you wish this to happen. However, we will not sell, distribute or lease your personal information to third parties for direct marketing purposes unless we have your permission or are required by law to do so.</p>
        <p>It is your right to request all or some of the information we hold specifically related to you, in order to review the information, have it modified, deleted or to forbid any further use of it by us. If you would like to review, modify or delete any data related to you held by us, you may send a request via email to <a href="mailto:hello@opensessions.io">hello@opensessions.io</a>&nbsp;titled “My Account Information”, and in the body of the email specify the nature of the request. Please send this request from the email address you have registered with on this site, in order for us to verify your identity before transmitting any data to you. If we cannot verify your identity, we maintain the right to deny your request until such a time as verification can be made.</p>
        <p>If a deletion request has been made, please note that we will anonymise or remove all of your identifying information within 10 business days of a request being made.</p>
        <p>If a subject access request is made (to review all the data held by us related to you), please allow 10 business days for us to respond to your request.</p>
        <h2>Security</h2>
        <p>We are committed to ensuring that your information is secure. In order to prevent unauthorised access or disclosure, we have put in place suitable physical, electronic and managerial procedures to safeguard and secure the information we collect online.</p>
        <h2>How do we use cookies?</h2>
        <p>A cookie is a small file which asks permission to be placed on your computer’s hard drive. Once you agree, the file is added and the cookie helps analyse web traffic or lets you know when you visit a particular site. Cookies allow web applications to respond to you as an individual. The web application can tailor its operations to your needs, likes and dislikes by gathering and remembering information about your preferences.</p>
        <p>Cookies help us make our website work better for you by enabling us to monitor which pages you find useful and which you do not. To do this, we use traffic log cookies to identify which pages are being used. This helps us analyse data about webpage traffic and improve our website in order to tailor it to your specific needs. We use this information for statistical analysis purposes only and then the data is removed from the system for good. A cookie in no way gives us access to your computer, nor any information about you other than the data you choose to share with us.</p>
        <p>You can choose to accept or decline cookies. Most web browsers automatically accept cookies, but you can usually modify your browser settings to decline cookies if you prefer. However, this may prevent you from taking full advantage of the website. Although we make use of cookies, most parts of the website can be accessed even if your cookies are disabled. With this in mind, you may come across parts of the site that you cannot access if your cookies are disabled.</p>
        <h2>Google Analytics</h2>
        <p>Google Analytics uses cookies to help us analyse how visitors use our services. The information generated by the cookie about your use of our website (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of this website, compiling reports on website activity and providing other services relating to website activity and Internet usage.Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf. Google will not associate your IP address with any other data held by Google. We hereby confirm that we use Google Analytics for Display Advertisers and its features and that we comply with the Google Analytics for Display Advertisers Policy. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above. For more information and how to opt-out, please see Google’s data, privacy and security information.</p>
        <h2>Improving Usability</h2>
        <p>This website uses FullStory, a service that allows IMIN LTD or London Sport Trading Ltd. to&nbsp;collect information from you concerning your use of this website and only this website, including but not limited to pages visited, links clicked, non-sensitive text entered, and mouse movements. FullStory is used to help IMIN LTD or London Sport Trading Ltd enhance or improve the user experience on this website and to perform any other function that IMIN LTD or London Sport Trading Ltd reasonably believe in good faith is required to protect and ensure the proper functionality and security of this website.</p>
        <blockquote>imin is the trading name of IMIN LTD, a company registered in England and &nbsp;Wales with Company Number 07716450.</blockquote>
        <blockquote>London Sport Trading Ltd is company registered in England and Wales with Company Number 09926559.</blockquote>
      </section>
    </div>);
  }
}
